[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
    base = '/'
    publish = 'dist/'
    command = 'npx pnpm i --store=node_modules/.pnpm-store && npm run build'

#[[headers]]
#  for = "/manifest.webmanifest"
#  [headers.values]
#    Content-Type = "application/manifest+json"