name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Packages
      run: |
        npm run bootstrap
    - name: Run build
      run: |
        npm run build